// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd2xNUDmQ7O3HRTARjqzqR4tjC7DuI-wA',
    appId: '1:124587175400:web:7d3806232ac7723984485d',
    messagingSenderId: '124587175400',
    projectId: 'fir-lessons-7c7c3',
    authDomain: 'fir-lessons-7c7c3.firebaseapp.com',
    storageBucket: 'fir-lessons-7c7c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0YsbBhF7Y4mVpSQbPCGVtjz3yK0Zslw',
    appId: '1:124587175400:android:e3935facda0b7b5084485d',
    messagingSenderId: '124587175400',
    projectId: 'fir-lessons-7c7c3',
    storageBucket: 'fir-lessons-7c7c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwcwJOEvaN9NFNHZN6fx2MaYU8itEOKo',
    appId: '1:124587175400:ios:74b9771433ea064384485d',
    messagingSenderId: '124587175400',
    projectId: 'fir-lessons-7c7c3',
    storageBucket: 'fir-lessons-7c7c3.appspot.com',
    iosClientId: '124587175400-gma2e57c9jdpni4a48ac3gaq23c5ihdc.apps.googleusercontent.com',
    iosBundleId: 'com.ayhanakkaya.firebaseLessons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwcwJOEvaN9NFNHZN6fx2MaYU8itEOKo',
    appId: '1:124587175400:ios:74b9771433ea064384485d',
    messagingSenderId: '124587175400',
    projectId: 'fir-lessons-7c7c3',
    storageBucket: 'fir-lessons-7c7c3.appspot.com',
    iosClientId: '124587175400-gma2e57c9jdpni4a48ac3gaq23c5ihdc.apps.googleusercontent.com',
    iosBundleId: 'com.ayhanakkaya.firebaseLessons',
  );
}
